Repository aeternity/aepp-base, pull requests merged in 2019-04, with the labels that each got.

#483 Safari iOS: Enable submitting for account renaming
  src/components/AeAccount.vue
Labels: review

#482 Cordova iOS: Fix visited link border color
  src/components/ListItem.vue
Labels: review

#484 Add pending transactions
  src/store/index.js
  src/store/utils.js
Labels: review

#502 ListItem: Disable icon shrinking
  src/components/ListItem.vue
Labels: review

#500 TabBar: Fix shadow around account switcher button
  src/components/mobile/TabBar.vue
Labels: review

#503 iOS build improvements
  .travis.yml
  package.json
Labels: review

#481 Cordova iOS: Fix wraping iframe if it width greater than viewport
  src/main.js
  src/pages/mobile/AppBrowser.vue
Labels: review

#509 Add time in transactions
  src/store/index.js
Labels: review

#512 mobile Page: Fix padding
  src/components/mobile/Page.vue
Labels: review

#514 Fix AeButton width in NetworkAdd component
  src/components/NetworkAdd.vue
Labels: review

#510 Avoid usage of old components package
  package-lock.json
  package.json
  src/App.vue
  src/components/AddressBookItem.vue
  src/components/AlertModal.vue
  src/components/ListItemAccount.vue
  src/components/desktop/FooterModal.vue
  src/components/desktop/SidebarModal.vue
  src/components/desktop/Step.vue
  src/components/desktop/WaitingForConfirmation.vue
  src/components/mobile/TabBar.vue
  src/pages/AddressBook.scss
  src/pages/AddressBook.vue
  src/pages/AddressBookChoose.vue
  src/pages/AddressBookNew.vue
  src/pages/AddressBookNoContacts.vue
Labels: review

#508 Fix address rendering in ConfirmSpendModal
  src/components/mobile/ConfirmModalAddress.vue
Labels: review

#504 Fix display of receive address
  src/components/mobile/AeAccountReverse.vue
  src/pages/mobile/Receive.vue
Labels: review

#507 Don't require PWA in development
  src/router/index.js
Labels: review

#477 Fix empty spaces on iPhone
  config.xml
  public/index.html
  src/App.vue
  src/components/ButtonAddFixed.vue
  src/components/TransferNotification.vue
  src/components/mobile/AccountSwitcher.vue
  src/components/mobile/Header.vue
  src/components/mobile/TabBar.vue
  src/pages/mobile/AppBrowser.vue
  src/pages/mobile/Intro.vue
  src/pages/mobile/Onboarding.vue
Labels: review

#519 AeInputMnemonic: Trim emitted value and submit on Enter press
  src/components/AeInputAddress.vue
  src/components/AeInputMnemonic.vue
  src/components/AeTextarea.vue
Labels: review

#506 mobile: Fix page height
  src/App.vue
Labels: review

#517 TabBar: Make it static on small screens
  src/components/mobile/TabBar.vue
Labels: review

#529 Update text on screens due to a new design
  src/components/TransferNotification.vue
  src/pages/AddressBookNew.vue
  src/pages/mobile/AppBrowser.vue
  src/pages/mobile/Receive.vue
  src/pages/mobile/Recover.vue
  src/pages/mobile/SettingsRemoteConnection.vue
  src/pages/mobile/Transfer.vue
Labels: review

#513 Change render engine to fix sticky positioning bug
  config.xml
Labels: review

#533 Disable broken features by UNFINISHED_FEATURES env variable
  .env
  .env.production
  src/AppDesktop.vue
  src/components/AeButton.vue
  src/components/ButtonPlain.vue
  src/components/desktop/Header.vue
  src/components/desktop/Sidebar.vue
  src/components/mobile/AccountSwitcher.vue
  src/components/mobile/TabBar.vue
  src/main.js
  src/pages/mobile/Settings.vue
  src/router/__tests__/index.js
  src/router/index.js
  src/router/routes/common.js
  src/router/routes/mobile.js
  tests/e2e/specs/migrations/fix-aes-ctr-counter-issue.js
  vue.config.js
Labels: review

#501 Update cordova-ios package
  .travis.yml
  config.xml
  package-lock.json
  package.json
  scripts/deploy.sh
  scripts/install.sh
Labels: review

#527 AePopover: Positioning fixes
  src/components/AePopover.vue
  src/stories/AePopover.stories.js
Labels: review

#516 Add Transaction History
  src/components/Guide.vue
  src/components/ListItem.vue
  src/components/ListItemTransaction.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/ConfirmContractCallModal.vue
  src/components/mobile/ConfirmContractDeployModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/ConfirmSpendModal.vue
  src/components/mobile/DetailsAddress.vue
  src/components/mobile/DetailsAmount.vue
  src/components/mobile/DetailsAmountAndFee.vue
  src/components/mobile/DetailsAmountFeeMixin.js
  src/components/mobile/DetailsFeeInput.vue
  src/components/mobile/DetailsField.vue
  src/components/mobile/DetailsFillMixin.js
  src/components/mobile/DetailsItem.vue
  src/components/mobile/DetailsPermission.vue
  src/components/mobile/DetailsRawData.vue
  src/components/mobile/DetailsRow.vue
  src/components/mobile/Page.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
  src/pages/mobile/Transfer.vue
  src/router/routes/mobile.js
  src/store/index.js
Labels: review

#538 travis ios: Enable deploy
  scripts/deploy.sh
Labels: review

#411 Add screens for AirGap setup process
  src/components/Guide.vue
  src/components/ListItemChoose.vue
  src/components/mobile/AccountSwitcher.vue
  src/pages/mobile/AccountsNew.vue
  src/pages/mobile/VaultSetup.scss
  src/pages/mobile/VaultSetupAnotherDevice.vue
  src/pages/mobile/VaultSetupAnotherDeviceGuide.vue
  src/pages/mobile/VaultSetupCompleted.vue
  src/pages/mobile/VaultSetupMethod.vue
  src/pages/mobile/VaultSetupSameDevice.vue
  src/router/routes/mobile.js
Labels: review

#539 Use patched cordova-plugin-wkwebview-engine package
  config.xml
Labels: review

#540 TransactionDetails: Show confirmation amount
  package-lock.json
  package.json
  src/main.js
  src/pages/mobile/TransactionDetails.vue
  src/store/index.js
Labels: review

#541 Refactoring and small updates
  config.xml
  scripts/before-deploy.sh
  src/store/index.js
Labels: review

#542 mobile Header: Show shadow of scrolled
  src/components/mobile/Header.vue
Labels: review

#545 travis install: Use prepare instead of rm/add
  package-lock.json
  package.json
  scripts/install.sh
Labels: review

#546 Fix versioning
  config.xml
  package-lock.json
  package.json
Labels: review

#544 cordova: Remove unused browser engine
  config.xml
Labels: review

#548 Refactor mobile modals
  package-lock.json
  package.json
  src/components/AeButton.vue
  src/components/AeModal.vue
  src/components/ModalPlain.vue
  src/components/Overlay.vue
  src/components/desktop/FooterModal.vue
  src/components/desktop/SidebarModal.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/MigratedBalanceModal.vue
  src/components/mobile/Modal.vue
  src/components/mobile/OverlayGrayscale.vue
  src/pages/mobile/AppBrowser.vue
  src/pages/mobile/Transfer.vue
  src/register-modals.js
Labels: review

#520 Make header smaller if it is empty
  src/components/mobile/ConfirmContractCallModal.vue
  src/components/mobile/ConfirmContractDeployModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/ConfirmSpendModal.vue
  src/components/mobile/Header.vue
Labels: review

#554 Fix exceptions on account creation and some other minor fixes
  src/components/AeFraction.vue
  src/components/AeInputAddress.vue
  src/components/AePopover.vue
  src/components/AppShortcut.vue
  src/components/ListItem.vue
  src/components/ModalPlain.vue
  src/components/Note.vue
  src/components/TransferNotification.vue
  src/components/desktop/Header.vue
  src/components/desktop/LedgerAddressConfirmModal.vue
  src/components/desktop/LedgerTransactionFeeModal.vue
  src/components/mobile/UrlForm.vue
  src/pages/desktop/Receive.vue
  src/pages/desktop/Settings.vue
  src/pages/mobile/AccountsNew.vue
  src/pages/mobile/AppBrowser.vue
  src/pages/mobile/NewAccountConfirm.vue
  src/pages/mobile/NewAccountCreate.vue
  src/pages/mobile/Recover.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/SetPassword.vue
  src/pages/mobile/Transfer.vue
  src/pages/mobile/VaultSetupAnotherDevice.vue
  src/pages/mobile/VaultSetupMethod.vue
  src/store/modules/mobile.js
  src/store/plugins/decryptAccounts.js
Labels: review

#562 Add custom scroll behavior
  src/router/index.js
Labels: review

#559 mobile Header: Use proper slot name
  src/components/mobile/Header.vue
Labels: review

#570 Reset SDK if can't connect to new network, add notification
  src/lib/networksRegistry.js
  src/store/plugins/initSdk.js
Labels: review

#573 NetworkAdd: Set maxLength to Node name
  src/components/NetworkAdd.vue
Labels: review

#511 Fix running on iOS 9.3
  package-lock.json
  package.json
  src/lib/setGlobalPolyfills.js
  src/main.js
  vue.config.js
Labels: review

#564 Use AccountInline instead combination of AeIdenticon and AeAddress
  src/components/AccountInline.vue
  src/components/Guide.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/ConfirmContractCallModal.vue
  src/components/mobile/ConfirmContractDeployModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/ConfirmSpendModal.vue
  src/pages/desktop/Send.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/SendAmount.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
Labels: review

#575 Browser wording update
  src/components/mobile/UrlForm.vue
  src/pages/mobile/Apps.vue
Labels: review

#549 Update balances using rxjs
  config/storybook/webpack.config.js
  package.json
  src/App.vue
  src/__mocks__/observables.js
  src/components/AeInputAddress.vue
  src/components/__tests__/AeInputAddress.js
  src/components/desktop/AccountSwitcher.vue
  src/components/mobile/AccountSwitcher.vue
  src/init.js
  src/main.js
  src/observables.js
  src/pages/desktop/Send.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/SendAmount.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
  src/pages/mobile/Transfer.vue
  src/router/__tests__/index.js
  src/store/index.js
  src/store/plugins/__tests__/pollBalance.js
  src/store/plugins/pollBalance.js
  src/stories/AeInputAddress.stories.js
Labels: priority, review

#547 Update SDK to 2.4.1
  package-lock.json
  package.json
  src/store/plugins/initSdk.js
Labels: priority, review

#543 [Dependency] Update cordova-android to 8.0.0
  Dockerfile.ci
  config.xml
  package-lock.json
  package.json
Labels: priority, review

#556 Account discovery, complete reset from Settings, state renamings
  src/lib/networksRegistry.js
  src/pages/mobile/AccountsNew.vue
  src/pages/mobile/Intro.vue
  src/pages/mobile/Login.vue
  src/pages/mobile/SetPassword.vue
  src/pages/mobile/Settings.vue
  src/router/__tests__/index.js
  src/router/routes/mobile.js
  src/router/utils.js
  src/store/index.js
  src/store/migrations/fix-aes-ctr-counter-issue.js
  src/store/modules/mobile.js
  src/store/modules/root.js
  src/store/plugins/decryptAccounts.js
  src/store/plugins/initSdk.js
  src/store/plugins/persistState.js
  src/store/utils.js
  tests/e2e/specs/migrations/fix-aes-ctr-counter-issue.js
Labels: review

#578 desktop: Fix observables usage
  config/storybook/webpack.config.js
  package.json
  src/__mocks__/observables.js
  src/components/AeInputAddress.vue
  src/components/__tests__/AeInputAddress.js
  src/components/desktop/AccountSwitcher.vue
  src/components/desktop/Header.vue
  src/components/mobile/AccountSwitcher.vue
  src/init.js
  src/main.js
  src/observables.js
  src/pages/desktop/Send.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/SendAmount.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
  src/pages/mobile/Transfer.vue
  src/router/__tests__/index.js
  src/store/index.js
  src/store/plugins/observables.js
  src/stories/AeInputAddress.stories.js
Labels: review

#577 Fix long networks names
  src/App.vue
  src/components/ListItem.vue
  src/components/NetworkAdd.vue
Labels: review

#586 updateTransactions: Update mdv api, drop unnecessary request
  src/store/modules/root.js
Labels: review

#565 Use css variables in Details components, sync with designs
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/DetailsAddress.vue
  src/components/mobile/DetailsAmount.vue
  src/components/mobile/DetailsAmountAndFee.vue
  src/components/mobile/DetailsFeeInput.vue
  src/components/mobile/DetailsField.vue
  src/components/mobile/DetailsFillMixin.js
  src/components/mobile/DetailsItem.vue
  src/components/mobile/DetailsPermission.vue
  src/components/mobile/DetailsRawData.vue
  src/pages/mobile/TransactionDetails.vue
Labels: review

#222 remote connection: Offline work and push notifications
  .env
  scripts/before-deploy.sh
  src/components/desktop/ConnectGuide.vue
  src/service-worker.js
  src/store/index.js
  src/store/modules/desktop.js
  src/store/modules/root.js
  src/store/plugins/registerServiceWorker.js
  src/store/plugins/remoteConnection.js
  vue.config.js
Labels: feature, review

#528 mobile Page: Make footer sticky
  package-lock.json
  package.json
  src/App.vue
  src/components/mobile/AccountSwitcher.vue
  src/components/mobile/AccountSwitcherModal.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/ConfirmContractCallModal.vue
  src/components/mobile/ConfirmContractDeployModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/ConfirmSpendModal.vue
  src/components/mobile/MigratedBalanceModal.vue
  src/components/mobile/Modal.vue
  src/components/mobile/OverlayGrayscale.vue
  src/components/mobile/Page.vue
  src/components/mobile/TabBar.vue
  src/pages/mobile/AppBrowser.vue
  src/pages/mobile/Intro.vue
  src/pages/mobile/Login.vue
  src/pages/mobile/NewAccount.vue
  src/pages/mobile/NewAccountConfirm.vue
  src/pages/mobile/NewAccountCreate.vue
  src/pages/mobile/Recover.vue
  src/pages/mobile/SetPassword.vue
  src/pages/mobile/Transfer.vue
  src/register-modals.js
  src/router/routes/common.js
  src/router/routes/mobile.js
  src/store/plugins/initSdk.js
  src/store/plugins/modals.js
Labels: review

#611 Fix route if not logged in on desktop
  src/router/index.js
Labels: review

#605 Observable variables fixes
  package-lock.json
  package.json
  src/store/plugins/observables.js
Labels: review

#606 Fix modals on desktop
  src/AppDesktop.vue
  src/components/desktop/LedgerModal.vue
Labels: review

#609 ConfirmSpendModal: Show payload if present
  src/components/mobile/ConfirmSpendModal.vue
Labels: review

#610 Most simplest implementation of Reverse iframe
  src/lib/initEnv.js
  src/store/index.js
  src/store/plugins/initSdk.js
  src/store/plugins/ledgerConnection.js
  src/store/plugins/reverseIframe.js
Labels: review

#612 Use cordova-res package to generate icons and splash screens
  .gitignore
  package-lock.json
  package.json
  resources/icon.png
  resources/splash.png
  splash.png
Labels: review

#613 Hide splash screen spinner
  config.xml
Labels: review

#617 Update SDK to 3.0.0
  package-lock.json
  package.json
Labels: review

#620 Add view in history button
  src/components/TransferNotification.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
  src/store/modules/root.js
Labels: review

#619 Rename identities to accounts
  src/components/AccountInline.vue
  src/components/ListItemTransaction.vue
  src/components/NetworkAdd.vue
  src/components/NetworkSwitcher.vue
  src/components/desktop/AccountSwitcher.vue
  src/components/desktop/Sidebar.vue
  src/components/mobile/AccountSwitcherModal.vue
  src/components/mobile/AeAccountReverse.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/ConfirmContractCallModal.vue
  src/components/mobile/ConfirmContractDeployModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/ConfirmSpendModal.vue
  src/components/mobile/DetailsAmountFeeMixin.js
  src/components/mobile/MigratedBalanceModal.vue
  src/components/mobile/TabBar.vue
  src/pages/desktop/Receive.vue
  src/pages/mobile/Receive.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/Transfer.vue
  src/store/index.js
  src/store/modules/mobile.js
  src/store/modules/root.js
  src/store/plugins/initSdk.js
  src/store/plugins/ledgerConnection.js
  src/store/plugins/observables.js
  src/store/plugins/remoteConnection.js
  src/store/plugins/reverseIframe.js
  src/stories/AeModal.stories.js
  src/stories/mobile/ConfirmModal.stories.js
Labels: review

#614 Fix splash screen by enabling SplashMaintainAspectRatio
  config.xml
Labels: review

#626 Fix state syncing
  src/store/plugins/remoteConnection.js
Labels: review

#627 Fix view in history on a dekstop
  src/components/TransferNotification.vue
Labels: review

#630 Update SDK to 3.1.0
  package-lock.json
  package.json
Labels: review

#618 desktop Settings: Add Reset option
  src/pages/desktop/Settings.vue
  src/router/index.js
  src/store/modules/mobile.js
  src/store/modules/root.js
  src/store/plugins/remoteConnection.js
  src/store/utils.js
Labels: review

#632 initSdk: Avoid account address confirmation in reverse iframe mode
  src/store/plugins/initSdk.js
Labels: review

#631 Rerender AeQrCode on size changing
  src/components/AeQrCode.vue
  src/stories/AeQrCode.stories.js
Labels: review

#628 Cancelable requests of rpc peers
  src/AppDesktop.vue
  src/components/desktop/CancelSignModal.vue
  src/components/desktop/FooterDesktop.vue
  src/components/desktop/WaitingForConfirmation.vue
  src/lib/__tests__/rpc.js
  src/lib/rpc.js
  src/register-modals.js
  src/store/plugins/initSdk.js
  src/store/plugins/remoteConnection.js
Labels: review

#642 AeInputRange: Fix styles
  src/components/AeInputRange.vue
Labels: review

#655 Update vee-validate to 2.2.5
  package-lock.json
  package.json
Labels: review

#656 inactiveAccounts: emits value even if only one account
  src/store/plugins/__tests__/observables.js
  src/store/plugins/observables.js
Labels: review

#644 Refactor accounts
  src/components/AccountInline.vue
  src/components/ListItemTransaction.vue
  src/components/desktop/AccountSwitcher.vue
  src/components/desktop/Sidebar.vue
  src/components/mobile/AccountSwitcherModal.vue
  src/components/mobile/AeAccountReverse.vue
  src/components/mobile/ConfirmAccountAccessModal.vue
  src/components/mobile/ConfirmSignModal.vue
  src/components/mobile/DetailsAmountFeeMixin.js
  src/components/mobile/MigratedBalanceModal.vue
  src/components/mobile/TabBar.vue
  src/pages/desktop/Receive.vue
  src/pages/desktop/Settings.vue
  src/pages/mobile/AccountsNew.vue
  src/pages/mobile/Intro.vue
  src/pages/mobile/Login.vue
  src/pages/mobile/Receive.vue
  src/pages/mobile/Send.vue
  src/pages/mobile/SendConfirm.vue
  src/pages/mobile/SetPassword.vue
  src/pages/mobile/Settings.vue
  src/pages/mobile/TransactionDetails.vue
  src/pages/mobile/TransactionList.vue
  src/pages/mobile/Transfer.vue
  src/router/__tests__/index.js
  src/router/routes/mobile.js
  src/router/utils.js
  src/store/index.js
  src/store/migrations/00-fix-aes-ctr-counter-issue.js
  src/store/migrations/01-reset-apps-state-field.js
  src/store/migrations/02-build-accounts-array.js
  src/store/migrations/__tests__/00-fix-aes-ctr-counter-issue.js
  src/store/migrations/__tests__/fix-aes-ctr-counter-issue.js
  src/store/migrations/fix-aes-ctr-counter-issue.js
  src/store/migrations/index.js
  src/store/modules/accounts/hdWallet.js
  src/store/modules/accounts/index.js
  src/store/modules/accounts/ledger.js
  src/store/modules/accounts/utils.js
  src/store/modules/desktop.js
  src/store/modules/mobile.js
  src/store/modules/root.js
  src/store/plugins/initSdk.js
  src/store/plugins/ledgerConnection.js
  src/store/plugins/observables.js
  src/store/plugins/persistState.js
  src/store/plugins/remoteConnection.js
  src/store/plugins/reverseIframe.js
  src/store/plugins/syncLedgerAccounts.js
  src/store/utils.js
  tests/e2e/specs/migrations/00-fix-aes-ctr-counter-issue.js
  tests/e2e/specs/migrations/02-build-accounts-array.js
Labels: review

#657 Update splash screen
  resources/splash.png
Labels: review

#647 Change network on network remove
  src/components/NetworkSwitcher.vue
Labels: review

#658 Fix observables tests
  src/store/plugins/__tests__/observables.js
Labels: review
